Repository UQdeco2800/2021-studio-3, pull requests merged in 2021-10, with the labels that each got.

#137 level 2 backerground music
  source/core/assets/sounds/level2.mp3
  source/core/src/main/com/deco2800/game/areas/LevelTwoArea.java
  source/core/src/main/com/deco2800/game/components/maingame/PauseGameDisplay.java
  source/core/src/main/com/deco2800/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
Labels: Team-3, Sprint 3

#135 UI changes
  source/core/assets/images/loading3.png
  source/core/src/main/com/deco2800/game/GdxGame.java
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/components/maingame/PopupMenuActions.java
  source/core/src/main/com/deco2800/game/components/mainmenu/LoadingDisplay.java
  source/core/src/main/com/deco2800/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/deco2800/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/deco2800/game/screens/LoadingScreen.java
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
  source/core/src/main/com/deco2800/game/screens/MainMenuScreen.java
  source/core/src/main/com/deco2800/game/services/ResourceService.java
  source/core/src/test/com/deco2800/game/components/maingame/PlayerWinActionsTest.java
  source/core/src/test/com/deco2800/game/components/maingame/PopupMenuActionsTest.java
Labels: Task, Team-3, Sprint 3

#139 Loading screen
  source/core/src/main/com/deco2800/game/GdxGame.java
  source/core/src/main/com/deco2800/game/areas/LevelThreeArea.java
  source/core/src/main/com/deco2800/game/areas/LevelTwoArea.java
  source/core/src/main/com/deco2800/game/components/maingame/PopupMenuActions.java
  source/core/src/main/com/deco2800/game/screens/LevelThreeScreen.java
  source/core/src/main/com/deco2800/game/screens/LevelTwoScreen.java
  source/core/src/main/com/deco2800/game/screens/LoadingScreen.java
Labels: Task, Team-3, Sprint 3

#142 Fixed game-crashing bug
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/screens/LoadingScreen.java
Labels: bug, Team-3, Sprint 3

#145 Merge playerStateAnimations into Main
  source/core/assets/images/Death.png
  source/core/assets/images/DeathFrame.png
  source/core/assets/images/IdleCharacters.atlas
  source/core/assets/images/IdleCharacters.png
  source/core/assets/images/Jump.atlas
  source/core/assets/images/JumpDamage(10-50).atlas
  source/core/assets/images/JumpDamage(50-90).atlas
  source/core/assets/images/PlayerMovementAnimations.atlas
  source/core/assets/images/Sprint.atlas
  source/core/assets/images/SprintDamage(10-50).atlas
  source/core/assets/images/SprintDamage(50-90).atlas
  source/core/assets/images/WalkingDamage50-10.atlas
  source/core/assets/images/WalkingDamage90-50.atlas
  source/core/src/main/com/deco2800/game/screens/LoadingScreen.java
Labels: Team-1, Sprint 3

#143 Implemented Player Roll Functionality
  source/core/assets/images/PlayerMovementAnimations.atlas
  source/core/assets/images/double_jump.atlas
  source/core/assets/images/double_jump.png
  source/core/assets/images/instence_fall.atlas
  source/core/assets/images/instence_fall.png
  source/core/assets/images/roll.atlas
  source/core/assets/images/roll.png
  source/core/assets/sounds/level3.mp3
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/areas/LevelThreeArea.java
  source/core/src/main/com/deco2800/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/deco2800/game/components/player/PlayerActions.java
  source/core/src/main/com/deco2800/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/deco2800/game/components/player/RollComponent.java
  source/core/src/main/com/deco2800/game/entities/factories/ObstacleFactory.java
  source/core/src/main/com/deco2800/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/deco2800/game/screens/LoadingScreen.java
  source/core/src/test/com/deco2800/game/components/player/RollComponentTest.java
Labels: Task, Team-3, Sprint 3

#149 UI changes
  source/core/assets/images/bar1.png
  source/core/assets/images/bar10.png
  source/core/assets/images/bar2.png
  source/core/assets/images/bar3.png
  source/core/assets/images/bar4.png
  source/core/assets/images/bar5.png
  source/core/assets/images/bar6.png
  source/core/assets/images/bar7.png
  source/core/assets/images/bar8.png
  source/core/assets/images/bar9.png
  source/core/assets/images/loadingF1.png
  source/core/src/main/com/deco2800/game/components/maingame/PopupMenuActions.java
  source/core/src/main/com/deco2800/game/components/mainmenu/LoadingDisplay.java
  source/core/src/main/com/deco2800/game/entities/factories/ObstacleFactory.java
  source/core/src/main/com/deco2800/game/screens/LoadingScreen.java
Labels: Task, Team-3, Sprint 3

#154 Fixing small UI bug
  source/core/src/main/com/deco2800/game/components/player/RollComponent.java
Labels: Task, Team-3, Sprint 3

#155 UI changes
  source/core/assets/level-floors/levelOne.txt
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/areas/LevelTwoArea.java
  source/core/src/main/com/deco2800/game/areas/terrain/TerrainFactory.java
  source/core/src/main/com/deco2800/game/components/mainmenu/LoadingDisplay.java
  source/core/src/main/com/deco2800/game/screens/LoadingScreen.java
Labels: bug, Team-3, Sprint 3

#157 Additional player movements
  source/core/assets/sounds/loss.mp3
  source/core/assets/sounds/win.mp3
Labels: Team-3, Sprint 3

#159 Title sequence
  source/core/assets/images/main_screens-01.png
  source/core/assets/images/main_screens-02.png
  source/core/assets/images/screen1.png
  source/core/assets/images/screen2.png
  source/core/assets/images/screen3.png
  source/core/assets/images/screen4.png
  source/core/assets/images/screen5.png
  source/core/assets/images/vikings_in_space.png
  source/core/src/main/com/deco2800/game/GdxGame.java
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/areas/LevelThreeArea.java
  source/core/src/main/com/deco2800/game/areas/terrain/TerrainFactory.java
  source/core/src/main/com/deco2800/game/components/mainmenu/IntroDisplay.java
  source/core/src/main/com/deco2800/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/deco2800/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/deco2800/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/deco2800/game/screens/IntroScreen.java
  source/core/src/main/com/deco2800/game/screens/LoadingScreen.java
Labels: Team-5, Feature, Task, Sprint 3

#188 Fixed lives bug, lives system works for all levels
  source/core/src/main/com/deco2800/game/GdxGame.java
  source/core/src/main/com/deco2800/game/components/maingame/PopupMenuActions.java
  source/core/src/main/com/deco2800/game/components/maingame/PopupMenuActionsLevel2.java
  source/core/src/main/com/deco2800/game/screens/LevelThreeScreen.java
  source/core/src/main/com/deco2800/game/screens/LevelTwoScreen.java
  source/core/src/main/com/deco2800/game/screens/LoadingScreen.java
Labels: bug, Sprint 4

#191 add background music for the loading screen and intro story screen
  source/core/assets/sounds/intro_story_background_music.mp3
  source/core/assets/sounds/loading_background_music.mp3
  source/core/src/main/com/deco2800/game/components/mainmenu/IntroDisplay.java
  source/core/src/main/com/deco2800/game/components/mainmenu/LoadingDisplay.java
  source/core/src/main/com/deco2800/game/screens/IntroScreen.java
  source/core/src/main/com/deco2800/game/screens/LoadingScreen.java
Labels: Task, Team-2, Sprint 4

#210 Multiple levels
  source/core/assets/level-floors/levelOne.txt
  source/core/assets/level-floors/levelOneGround.txt
  source/core/assets/level-floors/levelOneSky.txt
  source/core/assets/level-floors/levelTwoGround.txt
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/areas/terrain/TerrainFactory.java
  source/core/src/main/com/deco2800/game/components/player/RollComponent.java
  source/core/src/test/com/deco2800/game/components/player/RollComponentTest.java
Labels: Task, Team-3, Sprint 4

#237 upload two background music for level 4 and implement with the first one
  source/core/assets/sounds/level4_background_music_1.mp3
  source/core/assets/sounds/level4_background_music_2.mp3
  source/core/src/main/com/deco2800/game/areas/LevelFourArea.java
  source/core/src/main/com/deco2800/game/screens/LoadingScreen.java
Labels: Team-2, Sprint 4

#246 Death wall
  assets/wiki/user_test_results.png
  source/core/assets/saves/saveOne.txt
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/components/SprintComponent.java
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
Labels: bug, Team-1, Sprint 4

#258 Implemented all game levels
  source/core/assets/level-floors/levelFourFloat.txt
  source/core/assets/level-floors/levelFourGround.txt
  source/core/assets/level-floors/levelOneFloat.txt
  source/core/assets/level-floors/levelThreeFloat.txt
  source/core/assets/level-floors/levelThreeGround.txt
  source/core/assets/level-floors/levelThreeSky.txt
  source/core/assets/level-floors/levelTwoFloat.txt
  source/core/assets/level-floors/levelTwoGround.txt
  source/core/assets/level-floors/levelTwoSky.txt
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/areas/LevelFourArea.java
  source/core/src/main/com/deco2800/game/areas/LevelThreeArea.java
  source/core/src/main/com/deco2800/game/areas/LevelTwoArea.java
  source/core/src/main/com/deco2800/game/areas/terrain/TerrainFactory.java
  source/core/src/main/com/deco2800/game/components/maingame/BuffManager.java
  source/core/src/main/com/deco2800/game/components/maingame/PopupMenuActions.java
  source/core/src/test/com/deco2800/game/areas/ForestGameAreaTest.java
  source/core/src/test/com/deco2800/game/areas/LevelFourAreaTest.java
  source/core/src/test/com/deco2800/game/areas/LevelThreeAreaTest.java
  source/core/src/test/com/deco2800/game/areas/LevelTwoAreaTest.java
  source/core/src/test/com/deco2800/game/components/maingame/PopupMenuActionsTest.java
Labels: Task, Team-3, Sprint 4

#262 Origin/sound effect
  .DS_Store
  source/core/assets/sounds/click1.mp3
  source/core/assets/sounds/loss.mp3
  source/core/assets/sounds/win.mp3
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/areas/LevelThreeArea.java
  source/core/src/main/com/deco2800/game/components/maingame/PauseGameActions.java
  source/core/src/main/com/deco2800/game/components/maingame/PauseGameDisplay.java
  source/core/src/main/com/deco2800/game/components/maingame/PauseGamePopUp.java
  source/core/src/main/com/deco2800/game/components/maingame/PlayerLossDisplay.java
  source/core/src/main/com/deco2800/game/components/maingame/PlayerWinDisplay.java
  source/core/src/main/com/deco2800/game/components/maingame/PopupMenuActions.java
  source/core/src/main/com/deco2800/game/components/mainmenu/IntroDisplay.java
  source/core/src/main/com/deco2800/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/deco2800/game/components/player/PlayerWinPopup.java
  source/core/src/main/com/deco2800/game/screens/IntroScreen.java
  source/core/src/main/com/deco2800/game/screens/LoadScreen.java
  source/core/src/main/com/deco2800/game/screens/LoadingScreen.java
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
  source/core/src/main/com/deco2800/game/screens/MainMenuScreen.java
Labels: Task, Team-3, Sprint 4

#282 Altered player's life back to original value
  source/core/assets/saves/saveOne.txt
  source/core/src/main/com/deco2800/game/SaveData/SaveData.java
  source/core/src/main/com/deco2800/game/entities/factories/PlayerFactory.java
Labels: Task, Team-3, Sprint 4
